POST http://localhost:5000/api/v1.0/youtube/crawler
Accept: application/json
Content-Type: application/json


{
  "channelList": [
    {
      "channelId": "UC4rHBMP2rGPuFk9F-JlGzbQ",
      "crawlerType": 1,
      "fullLimit": 10
    }
  ]
}

<> 2022-04-24T142920.200.json
<> 2022-04-24T142919.200.json
<> 2022-04-24T142918.200.json
<> 2022-04-24T142917-1.200.json
<> 2022-04-24T142917.200.json
<> 2022-04-24T142916.200.json
<> 2022-04-24T142915.200.json
<> 2022-04-24T142914.200.json
<> 2022-04-24T142913.200.json
<> 2022-04-24T142911.200.json
<> 2022-04-24T142910.200.json
<> 2022-04-24T142745.200.json
<> 2022-04-24T142744.200.json
<> 2022-04-24T142743.200.json
<> 2022-04-24T142742.200.json
<> 2022-04-24T142713.200.json
<> 2022-04-24T142712.200.json
<> 2022-04-24T142711.200.json
<> 2022-04-24T142710.200.json
<> 2022-04-24T142709-1.200.json
<> 2022-04-24T142709.200.json
<> 2022-04-24T142708.200.json
<> 2022-04-24T142654.200.json
<> 2022-04-24T142645.200.json
<> 2022-04-24T142644.200.json
<> 2022-04-24T142629.200.json
<> 2022-04-24T142628.200.json
<> 2022-04-24T142627-1.200.json
<> 2022-04-24T142627.200.json
<> 2022-04-24T142626.200.json
<> 2022-04-24T142625.200.json
<> 2022-04-24T142624.200.json
<> 2022-04-24T142607.200.json
<> 2022-04-24T142606.200.json
<> 2022-04-24T142605.200.json
<> 2022-04-24T142604-1.200.json
<> 2022-04-24T142604.200.json
<> 2022-04-24T142603.200.json
<> 2022-04-24T142602.200.json
<> 2022-04-24T142601-1.200.json
<> 2022-04-24T142601.200.json
<> 2022-04-24T142600.200.json
<> 2022-04-24T142559.200.json
<> 2022-04-24T142558.200.json
<> 2022-04-24T142339.200.json
<> 2022-04-24T142337.200.json
<> 2022-04-24T142333.200.json
<> 2022-04-24T142332-1.200.json
<> 2022-04-24T142332.200.json
<> 2022-04-24T142331.200.json

### 视频检测
POST http://127.0.0.1:5000/api/v1.0/youtube/detect
Accept: application/json
Content-Type: application/json


[
  {
    "videoId": "kig_BIbETQ8"
  },
  {
    "videoId": "ZxGpAlK7Ko0"
  },
  {
    "videoId": "lHvTRdni1kw"
  },
  {
    "videoId": "dvK0lEvf9jk"
  },
  {
    "videoId": "_dbTqSTbjaY"
  },
  {
    "videoId": "Nr39A8WOTFM"
  },
  {
    "videoId": "HBY48MpKjNg"
  },
  {
    "videoId": "WuA_WfRyr7c"
  },
  {
    "videoId": "B4F_dn2DBf0"
  },
  {
    "videoId": "Kw5igd5aExg"
  },
  {
    "videoId": "LtXm75ancfk"
  },
  {
    "videoId": "aKLWqgxi9sk"
  },
  {
    "videoId": "2pWlMbM2kkU"
  },
  {
    "videoId": "8HSGaBAzTjs"
  },
  {
    "videoId": "esptpdQvluA"
  },
  {
    "videoId": "nkkHKDKznn0"
  },
  {
    "videoId": "KwZ9XAy2dqo"
  },
  {
    "videoId": "447JYM3Ynd0"
  },
  {
    "videoId": "U5p_oW1stus"
  },
  {
    "videoId": "yn_sqkZ_rSQ"
  },
  {
    "videoId": "S2C64UUw_ZI"
  },
  {
    "videoId": "F7xqJG9Wuno"
  },
  {
    "videoId": "1F_qnmrMcjA"
  },
  {
    "videoId": "IHltFzp3IWw"
  },
  {
    "videoId": "2pXUaPRv2UQ"
  },
  {
    "videoId": "ifOVWVEO9JU"
  },
  {
    "videoId": "m180LbK1OdI"
  },
  {
    "videoId": "udH598Dkg4g"
  },
  {
    "videoId": "TxaXEEr4RZ0"
  },
  {
    "videoId": "5LbwmAAtSmE"
  },
  {
    "videoId": "YJ6_CRTaxbs"
  },
  {
    "videoId": "yLQzZwCbXj0"
  },
  {
    "videoId": "1BxciOt_02Y"
  },
  {
    "videoId": "-5A9WF7fmpk"
  },
  {
    "videoId": "OcE-CuGwcMo"
  },
  {
    "videoId": "Xh-i9YJuya0"
  },
  {
    "videoId": "gydprobTuss"
  },
  {
    "videoId": "LRKOwHyGHHE"
  },
  {
    "videoId": "3DupEnVeZa4"
  },
  {
    "videoId": "EY7nXggTnYo"
  },
  {
    "videoId": "l7wFYVGzbKU"
  },
  {
    "videoId": "pd-fq76j10Q"
  },
  {
    "videoId": "81EvrJvCyFQ"
  },
  {
    "videoId": "qCmrqz6jbNo"
  },
  {
    "videoId": "_f1upGBEwoE"
  },
  {
    "videoId": "ceIm91XMgzQ"
  },
  {
    "videoId": "W7wNmQoOQtM"
  },
  {
    "videoId": "ka_hMx5psME"
  },
  {
    "videoId": "KIObnfGE2Qc"
  },
  {
    "videoId": "QGkErG9WzQs"
  },
  {
    "videoId": "0Qd919aDsgw"
  }
]
<> 2022-04-08T104604.200.json


### 博主同步
POST http://excontentcrawler-flask-dev.vivo.lan/api/v1.0/youtube/channelSync
Accept: application/json
Content-Type: application/json


{
  "channelList": [
    {
      "channelId": "UCQiUcScaD0BpM1wsCNArvPw",
      "region": "ID",
      "language": "in",
      "status": 0
    }
  ]
}

### 博主同步 local
POST http://172.22.224.74:5000/api/v1.0/youtube/channelSync
Accept: application/json
Content-Type: application/json


[{"channelId":"UCdvocMb6Vr1MdUmfxmSDhXA","channelTitle":"BLASTCINEMA","gmtCreate":1649729408000,"gmtModified":1649763005000,"id":17188,"language":"in","reason":0,"region":"ID","state":0,"subscriberCount":458000,"videoNum":270,"viewCount":72821565}]

### 博主下架
POST http://127.0.0.1:5000/api/v1.0/youtube/channelDown
Accept: application/json
Content-Type: application/json


{
  "channelList": [
    {
      "channelId": "UCO0msUgum-b22rx7520rGdg",
      "region": "ID"
    }
  ]
}

### 博主监控
POST http://127.0.0.1:5000/api/v1.0/youtube/influencerMonitor
Accept: application/json
Content-Type: application/json


{
  "channelList": [
    {
      "channelId": "UCO0msUgum-b22rx7520rGdg",
      "region": "ID"
    }
  ]
}

###
GET https://www.youtube.com/channel/UCJubjshqzd_ONByu6elgApQ/videos
